global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 's2s-backend'
    static_configs:
      - targets: ['host.docker.internal:8000']

  - job_name: 'redis'
    static_configs:
      - targets: ['host.docker.internal:6379']
